version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    user: 0:0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./data/prometheus:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.retention.time=36500d"
    networks:
      https_network:
        ipv4_address: 172.24.0.7
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - 9093:9093
    restart: always
    networks:
      https_network:
        ipv4_address: 172.24.0.11
  blackbox_exporter:
    image: prom/blackbox-exporter
    volumes:
      - ./config/blackbox_exporter.yml:/etc/blackbox_exporter/config.yml
    networks:
      https_network:
        ipv4_address: 172.24.0.12
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      https_network:
        ipv4_address: 172.24.0.8
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      https_network:
        ipv4_address: 172.24.0.9
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: 0:0
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      https_network:
        ipv4_address: 172.24.0.10
networks:
  https_network:
    external: true